name: nginx-microservices
services:
    nginx:
        build: ./Infra
        container_name: api_gateway_nginx
        ports:
            - 80:80
        networks:
            - network-bridge
        depends_on:
            - products_api
            - users_api
    products_api:
        build: ./src/Nginx.Microservices.Products.Api.AOT
        container_name: container_products_api
        networks:
            - network-bridge
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
    users_api:
        build: ./src/Nginx.Microservices.Users.Api.AOT
        container_name: container_users_api
        networks:
            - network-bridge
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
networks:
    network-bridge:
        driver: bridge